[project]
name = "yt-scraper"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "beautifulsoup4>=4.14.2",
    "ipython>=9.6.0",
    "openpyxl>=3.1.5",
    "pandas>=2.3.3",
    "patchright>=1.55.2",
]
